#!/bin/sh
cd examples
python ../src/Main.py "Pool_Testing"
python ../src/Main.py "Complex Probablistic Lockdown Model"
python ../src/Main.py "Example_1"
python ../src/Main.py "Stochastic_SIR"
python ../src/Main.py "Stochastic_SIR_two_events_alternating"
python ../src/Main.py "Scheduled_SEYAR"
python ../src/Main.py "Stochastic_SIR_random_graph"
python ../src/Main.py "Stochastic_SEYAR"
python ../src/Main.py "vaccination_policy_SIR"
python ../src/Main.py "Two_events_alternating_one_location"
python ../src/Main.py "sample campus"
python ../src/Main.py "Stochastic_SIR_two_locations"
python ../src/Main.py "Scheduled_SIR"
python ../src/Main.py "Policy_based_lockdown"
python ../src/Main.py "Example_2"
python ../src/Main.py "Scheduled_SEYAR_Interactions"
python ../src/Main.py "Stochastic_SIRID_variable_rates"
python ../src/Main.py "Example_3"
python ../src/Main.py "Two_events_alternating_with_intersection"
python ../src/Main.py "Two_independent_events_in_two_locations"
python ../src/Main.py "Stochastic_SIR_complete_graph"
