name: Testing

on: [push]
jobs:
  pre-commit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: pre-commit run --all-files
        run: |
          pre-commit run --all-files
  Code-Testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install main package
        run: |
          pip install -e .[test]
      - name: Run tests
        run: |
          pytest --cov=src --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
